# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e8538a7869d249b0985ce1aaeefeba24"
name = "banzai-apps"
handle = "banzai-apps"
application_url = "https://isolated-bryan-connecticut-logan.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_products, read_inventory, write_inventory, read_orders, write_orders, read_locations"

[auth]
redirect_urls = [
  "https://isolated-bryan-connecticut-logan.trycloudflare.com/auth/callback",
  "https://isolated-bryan-connecticut-logan.trycloudflare.com/auth/shopify/callback",
  "https://isolated-bryan-connecticut-logan.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
